# Automatically approve and merge PRs made by Dependabot

name: Dependabot

on:
  pull_request_target:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status:

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: octokit/request-action@v2.x
        if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review' }}
        env:
          GITHUB_TOKEN: ${{ secrets.FOXGLOVEBOT_GITHUB_TOKEN }}
        with:
          route: POST /repos/{owner_and_repo}/pulls/{pull_number}/reviews
          owner_and_repo: ${{ github.repository }}
          pull_number: ${{ github.event.pull_request.number }}
          event: "APPROVE"

      - uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.FOXGLOVEBOT_GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: squash
          MERGE_FORKS: false
          MERGE_FILTER_AUTHOR: "dependabot[bot]"
